volumes:
  gluetun_data:
    driver: local
  3x-ui_db:
    driver: local
  s-ui_db:
    driver: local
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local
  adguard_data:
    driver: local
  adguard_config:
    driver: local

networks:
  proxy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.39.0.0/24

services:
  # --- VPN Gateway ---
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports: # Choose random ports for maximum protection
      # Panel
      - "2053:2053" # 3x-ui
      - "2095:2095" # s-ui
      # Sub
      - "2054:2054" # 3x-ui
      - "2096:2096" # s-ui
      # Proxy
      - "2055:2055" # shadowsocks
      - "2056:2056" # vless
      - "2057:2057" # trojan
      - "2097:2097/udp" # hysteria2
    volumes:
      - gluetun_data:/gluetun
    environment:
      # --- VPN Configuration (Change these) ---
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=xxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxx=
      - WIREGUARD_ADDRESSES=10.14.0.2/16
      - SERVER_COUNTRIES=Netherlands # Choose the country where to connect to
      # --- DNS Configuration ---
      # Force Gluetun to use AdGuard Home for all DNS queries
      - DOT=off
      # - DNS_ADDRESS=172.38.0.3 # Static IP of AdGuard if needed
    networks:
      proxy-net:
        ipv4_address: 172.39.0.2
    restart: unless-stopped

  # --- Reverse Proxy and SSL ---
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    ports:
      - '80:80'   # Public HTTP
      - '443:443' # Public HTTPS
      - '81:81'   # Admin UI
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      proxy-net:
        ipv4_address: 172.39.0.3
    restart: unless-stopped

  # --- DNS Filtering ---
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - "53:53/tcp"
      - "53:53/udp"     # Standard DNS
      - "3000:3000/tcp" # Initial setup UI
      - "3001:3001/tcp" # Web UI
    volumes:
      - adguard_data:/opt/adguardhome/work
      - adguard_config:/opt/adguardhome/conf
      # - npm_letsencrypt:/etc/letsencrypt:ro # Mount NPM certs read-only for AdGuard UI if 853 port needed
    networks:
      proxy-net:
        ipv4_address: 172.39.0.4
    restart: unless-stopped

  # --- Proxy Applications ---
  3xui:
    build:
      context: https://github.com/procrastinando/ultimate-proxy-server.git#main
      dockerfile: Dockerfile-3xui
    container_name: 3x-ui
    volumes:
      - 3x-ui_db:/etc/x-ui/
      - npm_letsencrypt:/root/cert/:ro # Mount certs from NPM read-only
    tty: true
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - XUI_ENABLE_FAIL2BAN=true
    network_mode: service:gluetun
    restart: unless-stopped
    depends_on:
      - gluetun

  s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    volumes:
      - s-ui_db:/app/db
      - npm_letsencrypt:/app/cert:ro # Mount certs from NPM read-only
    tty: true
    network_mode: service:gluetun
    restart: unless-stopped
    depends_on:
      - gluetun
    entrypoint: "./entrypoint.sh"

